name: CI

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '18'
      - name: load configuration
        run: 'echo "$configuration" > ./packages/server/src/config/configuration.ts'
        shell: bash
        env:
          configuration: ${{secrets.DEV_SERVER_CONFIG}}
      - name: yarn install and CI
        run: |
          yarn install
          yarn global add lerna
          yarn lint

      - name: build
        run: |
          yarn build:admin
          yarn build:mobile
          yarn build:server
