name: dev-deploy

on:
  push:
    branches: ["dev"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - run: 'echo "$configuration" > configuration.ts'
        shell: bash
        env:
          configuration: ${{secrets.DEV_SERVER_CONFIG}}

      - name: Copy configuration file to remote
        uses: garygrossgarten/github-action-scp@release
        with:
          local: configuration.ts
          remote: github-action-deploy/packages/server/src/config/configuration.ts
          host: ${{ secrets.DEV_SERVER_SSH_HOST }}
          username: ${{ secrets.DEV_SERVER_SSH_USER }}
          password: ${{ secrets.DEV_SERVER_SSH_PASSWORD }}
          port: ${{ secrets.DEV_SERVER_SSH_PORT }}
      - name: run deploy
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.DEV_SERVER_SSH_HOST }}
          username: ${{ secrets.DEV_SERVER_SSH_USER }}
          password: ${{ secrets.DEV_SERVER_SSH_PASSWORD }}
          port: ${{ secrets.DEV_SERVER_SSH_PORT }}
          script: |
            cd github-action-deploy
            sh ./deploy.sh &
