name: dev-deploy

on:
  push:
    branches: ['dev']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Copy single file to remote
        uses: garygrossgarten/github-action-scp@release
        with:
          local: package.json
          remote: scp/single/package.json
          host: ${{ secrets.DEV_SERVER_SSH_HOST }}
          username: ${{ secrets.DEV_SERVER_SSH_USER }}
          password: ${{ secrets.DEV_SERVER_SSH_PASSWORD }}
